# Default values for hypergiga-tg-bot
replicaCount: 1

image:
  repository: hypergiga-tg-bot
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000
  metricsPort: 9090

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  NODE_ENV: production
  LOG_LEVEL: info
  LOG_PRETTY: "false"
  FEATURE_TRACING: "false"
  QUOTAS_DEFAULT: '{"daily_commands":1000,"daily_downloads":50,"daily_ai_requests":100,"daily_media_conversions":20}'
  RATE_LIMIT_GLOBAL: "1000"
  RATE_LIMIT_PER_USER: "100"
  RATE_LIMIT_PER_COMMAND: "10"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium"
  FFMPEG_PATH: "/usr/bin/ffmpeg"
  MAX_FILE_SIZE: "52428800"
  MAX_IMAGE_SIZE: "10485760"
  MAX_VIDEO_SIZE: "104857600"
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1000"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30000"
  DEBUG: "false"
  ENABLE_SWAGGER: "false"

secrets:
  telegramBotToken: ""
  databaseUrl: ""
  redisUrl: ""
  jwtSecret: ""
  encryptionKey: ""

postgresql:
  enabled: true
  auth:
    postgresPassword: "password"
    database: "hypergiga_bot"
  primary:
    persistence:
      enabled: true
      size: 8Gi

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 1Gi

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s

grafana:
  enabled: true
  adminPassword: "admin"
  persistence:
    enabled: true
    size: 1Gi